'use client';

import { 
  CalendarDaysIcon,
  HomeIcon,
  EnvelopeIcon,
  PhoneIcon,
  MapPinIcon,
  GlobeAltIcon,
  DocumentTextIcon,
  PhotoIcon,
  VideoCameraIcon,
  MusicalNoteIcon,
  ShoppingBagIcon,
  HeartIcon,
  StarIcon,
  BookmarkIcon,
  ShareIcon,
  ChatBubbleLeftRightIcon,
  UserIcon,
  CogIcon,
  BellIcon,
  MagnifyingGlassIcon,
  PlusIcon,
  MinusIcon,
  XMarkIcon,
  CheckIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  QuestionMarkCircleIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  ForwardIcon,
  BackwardIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  EyeIcon,
  EyeSlashIcon,
  LockClosedIcon,
  LockOpenIcon,
  KeyIcon,
  ShieldCheckIcon,
  FireIcon,
  BoltIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  BeakerIcon,
  WrenchIcon,
  PaintBrushIcon,
  ScissorsIcon,
  PencilIcon,
  TrashIcon,
  ArchiveBoxIcon,
  FolderIcon,
  DocumentIcon,
  FolderOpenIcon,
  PaperClipIcon,
  LinkIcon,
  ClipboardIcon,
  ClipboardDocumentIcon,
  ClipboardDocumentListIcon,
  ClipboardDocumentCheckIcon,
  CommandLineIcon,
  CodeBracketIcon,
  CodeBracketSquareIcon,
  ServerIcon,
  CpuChipIcon,
  CircleStackIcon,
  CloudArrowUpIcon,
  CloudArrowDownIcon,
  ArrowPathIcon,
  ArrowPathRoundedSquareIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ArrowUturnUpIcon,
  ArrowUturnDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDoubleUpIcon,
  ChevronDoubleDownIcon,
  Bars3Icon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3CenterLeftIcon,
  Bars4Icon,
  QueueListIcon,
  ListBulletIcon,
  Squares2X2Icon,
  SquaresPlusIcon,
  RectangleStackIcon,
  RectangleGroupIcon,
  SwatchIcon,
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  FunnelIcon,
  MagnifyingGlassMinusIcon,
  MagnifyingGlassPlusIcon,
  ViewfinderCircleIcon,
  CameraIcon,
  FilmIcon,
  MicrophoneIcon,
  RadioIcon,
  TvIcon,
  DevicePhoneMobileIcon,
  DeviceTabletIcon,
  ComputerDesktopIcon,
  PrinterIcon,
  WifiIcon,
  SignalIcon,
  Battery0Icon,
  Battery50Icon,
  Battery100Icon,
  PowerIcon,
  LightBulbIcon,
  SparklesIcon,
  GiftIcon,
  CakeIcon,
  TrophyIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  HandRaisedIcon,
  FingerPrintIcon,
  FaceSmileIcon,
  FaceFrownIcon,
} from '@heroicons/react/24/outline';

// Icon mapping for dynamic imports
const iconMap: Record<string, any> = {
  calendarDays: CalendarDaysIcon,
  home: HomeIcon,
  envelope: EnvelopeIcon,
  phone: PhoneIcon,
  mapPin: MapPinIcon,
  globeAlt: GlobeAltIcon,
  documentText: DocumentTextIcon,
  photo: PhotoIcon,
  videoCamera: VideoCameraIcon,
  musicalNote: MusicalNoteIcon,
  shoppingBag: ShoppingBagIcon,
  heart: HeartIcon,
  star: StarIcon,
  bookmark: BookmarkIcon,
  share: ShareIcon,
  chatBubbleLeftRight: ChatBubbleLeftRightIcon,
  user: UserIcon,
  cog: CogIcon,
  bell: BellIcon,
  magnifyingGlass: MagnifyingGlassIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  xMark: XMarkIcon,
  check: CheckIcon,
  exclamationTriangle: ExclamationTriangleIcon,
  informationCircle: InformationCircleIcon,
  questionMarkCircle: QuestionMarkCircleIcon,
  arrowRight: ArrowRightIcon,
  arrowLeft: ArrowLeftIcon,
  arrowUp: ArrowUpIcon,
  arrowDown: ArrowDownIcon,
  play: PlayIcon,
  pause: PauseIcon,
  stop: StopIcon,
  forward: ForwardIcon,
  backward: BackwardIcon,
  speakerWave: SpeakerWaveIcon,
  speakerXMark: SpeakerXMarkIcon,
  eye: EyeIcon,
  eyeSlash: EyeSlashIcon,
  lockClosed: LockClosedIcon,
  lockOpen: LockOpenIcon,
  key: KeyIcon,
  shieldCheck: ShieldCheckIcon,
  fire: FireIcon,
  bolt: BoltIcon,
  sun: SunIcon,
  moon: MoonIcon,
  cloud: CloudIcon,
  beaker: BeakerIcon,
  wrench: WrenchIcon,
  paintBrush: PaintBrushIcon,
  scissors: ScissorsIcon,
  pencil: PencilIcon,
  trash: TrashIcon,
  archiveBox: ArchiveBoxIcon,
  folder: FolderIcon,
  document: DocumentIcon,
  folderOpen: FolderOpenIcon,
  paperClip: PaperClipIcon,
  link: LinkIcon,
  clipboard: ClipboardIcon,
  clipboardDocument: ClipboardDocumentIcon,
  clipboardDocumentList: ClipboardDocumentListIcon,
  clipboardDocumentCheck: ClipboardDocumentCheckIcon,
  commandLine: CommandLineIcon,
  codeBracket: CodeBracketIcon,
  codeBracketSquare: CodeBracketSquareIcon,
  server: ServerIcon,
  cpuChip: CpuChipIcon,
  circleStack: CircleStackIcon,
  cloudArrowUp: CloudArrowUpIcon,
  cloudArrowDown: CloudArrowDownIcon,
  arrowPath: ArrowPathIcon,
  arrowPathRoundedSquare: ArrowPathRoundedSquareIcon,
  arrowUturnLeft: ArrowUturnLeftIcon,
  arrowUturnRight: ArrowUturnRightIcon,
  arrowUturnUp: ArrowUturnUpIcon,
  arrowUturnDown: ArrowUturnDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  chevronDown: ChevronDownIcon,
  chevronDoubleLeft: ChevronDoubleLeftIcon,
  chevronDoubleRight: ChevronDoubleRightIcon,
  chevronDoubleUp: ChevronDoubleUpIcon,
  chevronDoubleDown: ChevronDoubleDownIcon,
  bars3: Bars3Icon,
  bars3BottomLeft: Bars3BottomLeftIcon,
  bars3BottomRight: Bars3BottomRightIcon,
  bars3CenterLeft: Bars3CenterLeftIcon,
  bars4: Bars4Icon,
  queueList: QueueListIcon,
  listBullet: ListBulletIcon,
  squares2X2: Squares2X2Icon,
  squaresPlus: SquaresPlusIcon,
  rectangleStack: RectangleStackIcon,
  rectangleGroup: RectangleGroupIcon,
  swatch: SwatchIcon,
  adjustmentsHorizontal: AdjustmentsHorizontalIcon,
  adjustmentsVertical: AdjustmentsVerticalIcon,
  funnel: FunnelIcon,
  magnifyingGlassMinus: MagnifyingGlassMinusIcon,
  magnifyingGlassPlus: MagnifyingGlassPlusIcon,
  viewfinderCircle: ViewfinderCircleIcon,
  camera: CameraIcon,
  film: FilmIcon,
  microphone: MicrophoneIcon,
  radio: RadioIcon,
  tv: TvIcon,
  devicePhoneMobile: DevicePhoneMobileIcon,
  deviceTablet: DeviceTabletIcon,
  computerDesktop: ComputerDesktopIcon,
  printer: PrinterIcon,
  wifi: WifiIcon,
  signal: SignalIcon,
  battery0: Battery0Icon,
  battery50: Battery50Icon,
  battery100: Battery100Icon,
  power: PowerIcon,
  lightBulb: LightBulbIcon,
  sparkles: SparklesIcon,
  gift: GiftIcon,
  cake: CakeIcon,
  trophy: TrophyIcon,
  handThumbUp: HandThumbUpIcon,
  handThumbDown: HandThumbDownIcon,
  handRaised: HandRaisedIcon,
  fingerPrint: FingerPrintIcon,
  faceSmile: FaceSmileIcon,
  faceFrown: FaceFrownIcon,
};

export function getIcon(iconName: string, className: string = "w-6 h-6") {
  const IconComponent = iconMap[iconName];
  
  if (!IconComponent) {
    // Return a default icon if the requested icon is not found
    return <QuestionMarkCircleIcon className={className} />;
  }
  
  return <IconComponent className={className} />;
}

export function isValidIcon(iconName: string): boolean {
  return iconName in iconMap;
}

// Export available icon names for reference
export const availableIcons = Object.keys(iconMap).sort();
